group_id: 10
names:
- 陈琳
- 陈韫凌
- 冯晓菲
- 鲁静萍
- 吕一
- 李钊
- 潘瑛琪
- 祁静
- 宋昕冉
- 孙歆文
- 汪佳翎
- 王晓佳
- 谢天依
- 杨冰怡
- 张丹三
- 张嘉予
- 邵雪聪
- 李晶
- 林忆宁
- 汪束
- 杨韫玉

span: 2
directory: /home/PERSISTENT_STORAGE/downloads
naming:
perf:
